# Site settings
title: anna gong
email: agong1@hwemail.com
description: > # this means to ignore newlines until "baseurl:"
  Anna Gong's portfolio website for assorted artworks.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://byizzy.github.io/annagong" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
